import { FC, ReactNode } from "react";

import type { Metadata } from 'next'
import '../styles/globals.css'
import { AppProps } from "next/app"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  return <div>
    <Component {...pageProps} />
  </div>
}