import { FC, ReactNode } from "react";

import type { Metadata } from 'next'
import '../styles/globals.css'
import { AppProps } from "next/app"
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import MainLayout from "@/components/layout/MainLayout";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }: AppProps) {
  return <MainLayout>
      <Header></Header>
      <main className="flex-auto p-8 text-slate-200">
        <Component {...pageProps} />
      </main>
      <Footer></Footer>
  </MainLayout>
}